# Generated by Django 5.1.4 on 2025-01-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='imageUrl',
        ),
    ]
